### ISSUE TITLE
Old gnutls?

### ISSUE THREAD

**Issue by Trisk3lion** [juanjosegarciaripoll/emacs-build#1]
Hello, just something I that occured to med when using your release package. 

I had problems connecting to Melpa with SSL, by using https://, the error seemed to indicate gnutls so I downloaded the newest version from https://gnutls.org/download.html (3.7.0:mingw64) and replaced the files in /bin with those from the 3.7.0:mingw64 and that fixed the problem.

Just for your information!

**Comment by juanjosegarciaripoll** [comment]
I upgraded emacs-build with a new script that patches the TLS library. Thanks for reporting!

**Comment by Trisk3lion** [comment]
@juanjosegarciaripoll Great! That seems also have fixed the issue with pdftools not being included in the "Emacs + all extensions build".

**Comment by juanjosegarciaripoll** [comment]
The download link from gnutls no longer works. This fix is no longer operational.

**Comment by juanjosegarciaripoll** [comment]
Using the latest build and a stable release tag, gnutls from MINGW seems to work. I close this issue. Please reopen if you experience problems.
