### ISSUE TITLE
Instructions for uninstalling?

### ISSUE THREAD

**Issue by baracunatana** [juanjosegarciaripoll/emacs-build#4]
Hi

Thanks for this script. I'm looking to move away from wsl2 and this is a great way forward. However, what have to be done to uninstall the packages installed by this script? Is it just a matter of unstalling msys2?
Furthermore, once `pack-all` action is executed, can I delete the zip files?

I have little experience with msys2, so apologies for the noob question.

**Comment by juanjosegarciaripoll** [comment]
There is no installation. If you delete this directory, all the zip files and the msys2 local installation disappears (msys2 is unpacked in a subdirectory).
